alias xcode='open -a xcode'
alias diff='colordiff'
alias gimp='open -a gimp'
alias vi='vim'
alias tlmgr='/usr/share/texmf-dist/scripts/texlive/tlmgr.pl --usermode'
alias pcn='sudo pacman -Syu'
alias sap='sudo apt-get install'
