[icons]
# font awesome
urxvt = ""
chromium = ""
cantata = ""

[aliases]
TelegramDesktop = "Telegram"
"Org.gnome.Nautilus" = "Nautilus"

[general]
separator = "  "
default_icon = ""

[options]
remove_duplicates = true
use_instance = true
no_names = true
