# =========================================================================== #
# Library Settings General
# =========================================================================== #
directory: /media/hdd0/Music
library: ~/beetdb/musiclibrary.db

paths:
    default: $albumartist/$album%aunique{}/$track $title
    comp: Various Artists/$album%aunique{}/$track $title

import:
  move: yes

# =========================================================================== #
# Plugin Settings
# =========================================================================== #

# MPD
# =========================================================================== #
plugins: mpdupdate

mpd:
  host: 192.168.0.88
  port: 6600

# Discogs
# =========================================================================== #
plugins: discogs

  #discogs:
  #  user_token: eLSBECSjXYUWYLNzpyckOHUwEfjOAlqmFWCPtsJJ

# Bandcamp
# =========================================================================== #
plugins: bandcamp fromfilename

# Spotify
# =========================================================================== #
# Try out spotify plugin (Create spotify playlists from beets)
plugins: spotify

# Convert
# =========================================================================== #
plugins: convert

